# Generated by Django 2.1 on 2019-02-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uplifty', '0002_auto_20190222_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
