# Generated by Django 2.1 on 2019-02-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uplifty', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
